[project]
name = "lock-override-face-recognition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "insightface>=0.7.3",
    "mediapipe>=0.10.21",
    "onnxruntime>=1.22.1",
    "opencv-python>=4.11.0.86",
]
